// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');

(async () => {
  let driver;
  try {
    driver = await new Builder().forBrowser('chrome').build();
    await driver.get("http://localhost/multiflexi/logout.php");
    await driver.manage().window().maximize();

    // Handle GDPR consent banner
    try {
      const gdprAcceptButton = await driver.wait(until.elementLocated(By.id("consent-accept-all")), 3000);
      await gdprAcceptButton.click();
      await driver.sleep(500);
    } catch (e) {
      // GDPR banner might not be present
    }

     // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);

    // Optionally, check for successful login (adjust selector as needed)
    try {
      await driver.wait(until.elementLocated(By.id("usermenu")), 5000);
    } catch (e) {
      // Login failed
      if (driver) await driver.quit();
      process.exit(0);
    }

    if (driver) await driver.quit();
    process.exit(1); // Success: return 1
  } catch (error) {
    if (driver) await driver.quit();
    process.exit(0); // Error: return 0
  }
})();
