// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const fs = require('fs');
const path = '/tmp/multiflexi_admin_credentials.json';
const handleGdprConsent = require('./gdpr');

describe('login2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login2', async function() {
    await driver.get("https://vyvojar.spoje.net/multiflexi/login.php");

    // Handle GDPR consent banner
    await handleGdprConsent(driver);

    // Ensure credentials file exists
    if (!fs.existsSync(path)) {
      throw new Error(`Credentials file not found: ${path}`);
    }

    const creds = JSON.parse(fs.readFileSync(path, 'utf8'));
    console.log(`Using credentials: Username=${creds.username}, Password=${creds.password}`);

    // Use the exact username and password from the credentials file
    await driver.findElement(By.name("login")).click();
    await driver.findElement(By.name("login")).sendKeys(creds.username);
    await driver.findElement(By.name("password")).click();
    await driver.findElement(By.name("password")).sendKeys(creds.password);
    await driver.findElement(By.id("signinbuttonmenu")).click();

    // Optionally, check for successful login
    await driver.wait(until.elementLocated(By.id("usermenu")), 10000); // Increased timeout to 10 seconds
  })
})


