// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('companyappseput2', function() {
  this.timeout(60000); // Increased timeout to 60 seconds
  let driver
  let vars
  
  // Generate random text helper function
  function randomText(length = 4) {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
    let result = ''
    for (let i = 0; i < length; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length))
    }
    return result
  }
  
  beforeEach(async function() {
    console.log("Starting browser setup...");
    driver = await new Builder().forBrowser('chrome').build();
    vars = {};
    console.log("Browser setup complete.");
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('companyappseput2', async function() {
    console.log("Navigating to logout page...");
    await driver.get("https://vyvojar.spoje.net/multiflexi/logout.php")
    await driver.manage().window().maximize()
    console.log("Logout page loaded.");

    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
    console.log("GDPR consent handled.");

    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    console.log("Login successful.");

    // Wait for successful login and navigation to main page
    await driver.wait(until.urlContains("main.php"), 20000);
    console.log("Main page loaded.");

    await driver.findElement(By.id("imgwidth30srcimagescompanysvgCompanies")).click()
    await driver.wait(until.elementLocated(By.linkText("New Company")), 5000)
    await driver.findElement(By.linkText("New Company")).click()
    console.log("Navigated to New Company page.");

    await driver.findElement(By.id("Companyname")).sendKeys(randomText())
    await driver.findElement(By.id("savecompanybutton")).click()
    await driver.wait(until.elementLocated(By.id("imgwidth30srcimagesappssvgApplications")), 5000)
    console.log("Company saved.");

    await driver.findElement(By.id("imgwidth30srcimagesappssvgApplications")).click()
    await driver.wait(until.elementLocated(By.linkText("🧩Register Application")), 5000)
    await driver.findElement(By.linkText("🧩Register Application")).click()
    console.log("Navigated to Register Application page.");

    await driver.sleep(1000)
    await driver.wait(until.elementLocated(By.id("Configuration-tab")), 5000)
    await driver.findElement(By.id("Configuration-tab")).click()
    await driver.sleep(500)
    await driver.findElement(By.id("Applicationname")).click()
    await driver.findElement(By.id("Applicationname")).sendKeys(randomText())
    await driver.findElement(By.id("Applicationcode")).click()
    await driver.findElement(By.id("Applicationcode")).sendKeys(randomText())
    await driver.findElement(By.id("ApplicationDescription")).click()
    await driver.findElement(By.id("ApplicationDescription")).sendKeys(randomText())
    await driver.findElement(By.id("Pathtobinary")).click()
    await driver.findElement(By.id("Pathtobinary")).sendKeys(randomText())
    await driver.findElement(By.id("SetupCommand")).click()
    await driver.findElement(By.id("SetupCommand")).sendKeys(randomText())
    await driver.findElement(By.id("Commandarguments")).click()
    await driver.findElement(By.id("Commandarguments")).sendKeys(randomText())
    await driver.findElement(By.id("ApplicationHomepage")).click()
    await driver.findElement(By.id("ApplicationHomepage")).sendKeys(randomText())
    await driver.findElement(By.id("Containerimage")).click()
    await driver.findElement(By.id("Containerimage")).sendKeys(randomText())
    await driver.findElement(By.id("CurrentVersionofApplication")).click()
    await driver.findElement(By.id("CurrentVersionofApplication")).sendKeys(randomText())
    await driver.findElement(By.id("Applicationdeploycommand")).click()
    await driver.findElement(By.id("Applicationdeploycommand")).sendKeys(randomText())
    await driver.findElement(By.id("Reuqirements")).click()
    await driver.findElement(By.id("Reuqirements")).sendKeys(randomText())
    await driver.findElement(By.id("ApplicationUniversalUniqueIdentifier")).click()
    await driver.findElement(By.id("ApplicationUniversalUniqueIdentifier")).sendKeys(randomText())
    await driver.findElement(By.id("Topicsdividedbycolumn")).click()
    await driver.findElement(By.id("Topicsdividedbycolumn")).sendKeys(randomText())
    await driver.findElement(By.id("saveappbutton")).click()
    await driver.sleep(1000)
    await driver.findElement(By.id("imgwidth30srcimagescompanysvgCompanies")).click()
    await driver.findElement(By.linkText("Listing")).click()
    await driver.sleep(1000)
    
    // Find and click the last company's apps button
    const appsButtons = await driver.findElements(By.id("appscompanybutton"))
    if (appsButtons.length > 0) {
      await appsButtons[appsButtons.length - 1].click()
    }
    await driver.sleep(1000)
    
    // Select first available application
    const appCheckboxes = await driver.findElements(By.css("input[id^='app_']"))
    if (appCheckboxes.length > 0) {
      await appCheckboxes[0].click()
    }
    await driver.findElement(By.css(".btn-success")).click()
    await driver.sleep(1000)
    
    await driver.findElement(By.id("imgwidth30srcimagescompanysvgCompanies")).click()
    await driver.findElement(By.linkText("Listing")).click()
    await driver.sleep(1000)
    
    // Click on the last company to view details
    const companyLinks = await driver.findElements(By.css("tbody tr td:nth-child(2) > a"))
    if (companyLinks.length > 0) {
      await companyLinks[companyLinks.length - 1].click()
    }
    await driver.sleep(1000)
    
    await driver.findElement(By.css(".card-img-top")).click()
    await driver.findElement(By.linkText("⚗️ ➕ New RunTemplate")).click()
    await driver.findElement(By.linkText("Launch now")).click()
  })
})
