// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('allApplicationJobsHistory', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('allApplicationJobsHistory', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
      // GDPR banner might not be present
    
     // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Now test all application jobs history
    await driver.get("http://localhost/multiflexi/main.php")
    await driver.findElement(By.id("imgwidth30srcimagesappssvgApplications")).click()
    await driver.findElement(By.linkText("🧩Register Application")).click()
    
    // Wait for page to load
    await driver.sleep(1000)
    
    // Wait for Jobs tab to be clickable
    const jobsTab = await driver.wait(until.elementLocated(By.id("Jobs-tab")), 5000)
    await driver.wait(until.elementIsVisible(jobsTab), 5000)
    await driver.wait(until.elementIsEnabled(jobsTab), 5000)
    await jobsTab.click()
    
    // Wait and click all application jobs history button
    await driver.sleep(500)
    await driver.findElement(By.id("allapplicationjobshistorybutton")).click()
    
  // Try to click on the first job in the list if available
    try {
      const firstJob = await driver.findElement(By.css("table tbody tr:first-child a"))
      await firstJob.click()
    } catch (e) {
      // No jobs available, which is acceptable
    }
  })
})