// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('allJobs', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('allJobs', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
      // GDPR banner might not be present
    
    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Now test all jobs
    await driver.get("http://localhost/multiflexi/main.php")
    await driver.findElement(By.linkText("Home")).click()
    await driver.findElement(By.id("allJobsButton")).click()
    
    // Try to click on the first job in the list if available
    try {
      const firstJob = await driver.findElement(By.css("table tbody tr:first-child a"))
      await firstJob.click()
    } catch (e) {
      // No jobs available, which is acceptable
    }
  })
})
