// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('companyList', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('companyList', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
    
    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Now test company list
    await driver.get("http://localhost/multiflexi/main.php")
    await driver.findElement(By.id("imgwidth30srcimagescompanysvgCompanies")).click()
    await driver.findElement(By.linkText("Listing")).click()
    
    // Wait for the company list table to load
    await driver.sleep(1000)
    
    // Select the last company in the list using CSS selector
    const lastCompanyRow = await driver.findElement(By.css("table tbody tr:last-child"))
    await lastCompanyRow.click()
    
    // Wait to see the result
    await driver.sleep(1000)
  })
})
