// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('credentialTypeHelpers', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('credentialTypeHelpers', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
      // GDPR banner might not be present
    
    
    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Now test credential type helpers
    await driver.get("http://localhost/multiflexi/main.php")
    await driver.findElement(By.id("imgwidth30srcimagessystem-userssvgAdmin")).click()
    await driver.findElement(By.linkText("🔐 Credential Type helpers")).click()
  })
})
