// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('deshboardViewApps', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('deshboardViewApps', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
 
    
    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Now test dashboard view apps
    await driver.get("http://localhost/multiflexi/main.php")
    await driver.findElement(By.id("imgheight30srcimageslogsvgLogs")).click()
    await driver.findElement(By.linkText("📋 Dashboard")).click()
    await driver.findElement(By.id("viewappsbutton")).click()
    
    // Wait for the table to load and select first application in list using CSS selector
    await driver.sleep(1000)
    const firstAppLink = await driver.wait(until.elementLocated(By.css("tbody tr:first-child a")), 5000)
    await firstAppLink.click()
  })
})
