// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('editProfile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('editProfile', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
 
    
    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Now test edit profile
    await driver.get("http://localhost/multiflexi/main.php")
    await driver.findElement(By.linkText("Home")).click()
    await driver.findElement(By.id("editProfileButton")).click()
    await driver.findElement(By.name("lastname")).click()
    
    // Generate random lastname
    const randomLastname = "User_" + Math.random().toString(36).substring(2, 10)
    await driver.findElement(By.name("lastname")).sendKeys(randomLastname)
    await driver.findElement(By.id("saveuserchangesbutton")).click()
  })
})
