// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('newAdmin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('newAdmin', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
 
    
    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Generate random data
    const randomString = () => Math.random().toString(36).substring(2, 10)
    const randomNumber = () => Math.floor(1000 + Math.random() * 9000)
    const randomFirstname = "User" + randomString()
    const randomLastname = "Test" + randomNumber()
    const randomUsername = "admin" + randomString() + randomNumber()
    const randomPassword = "Pass" + randomString().toUpperCase() + randomNumber() + "!@"
    const randomEmail = "test" + randomString() + "@example.com"
    
    // Now test new admin creation
    await driver.get("http://localhost/multiflexi/main.php")
    await driver.findElement(By.id("imgwidth30srcimagessystem-userssvgAdmin")).click()
    await driver.findElement(By.linkText("🤬 New Admin")).click()
    await driver.findElement(By.id("Firstname")).click()
    await driver.findElement(By.id("Firstname")).sendKeys(randomFirstname)
    await driver.findElement(By.id("Lastname")).click()
    await driver.findElement(By.id("Lastname")).sendKeys(randomLastname)
    await driver.findElement(By.id("Username")).click()
    await driver.findElement(By.id("Username")).sendKeys(randomUsername)
    await driver.findElement(By.id("Password")).click()
    await driver.findElement(By.id("Password")).sendKeys(randomPassword)
    await driver.findElement(By.id("Passwordconfirmation")).click()
    await driver.findElement(By.id("Passwordconfirmation")).sendKeys(randomPassword)
    await driver.findElement(By.id("eMailaddress")).click()
    await driver.findElement(By.id("eMailaddress")).sendKeys(randomEmail)
    await driver.findElement(By.name("Register")).click()
  })
})
