// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('objednaciFormulaPage', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('objednaciFormulaPage', async function() {
    await driver.get("https://system.spoje.net/")
    await driver.manage().window().maximize()
    await driver.findElement(By.css("a:nth-child(2) .mpicon")).click()
    
    // Wait for login form to load
    await driver.sleep(2000)
    const usernameField = await driver.wait(until.elementLocated(By.name("username")), 5000)
    await usernameField.sendKeys("vyvojasystem@spojenet.cz")
    
    const passwordField = await driver.findElement(By.name("password"))
    await passwordField.sendKeys("@vx6nCDfBZVLhcLy")
    
    await driver.findElement(By.id("signin")).click()
    
    // Wait for login to complete
    await driver.sleep(2000)
  })
})
