// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('privacyPreferences', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('privacyPreferences', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
      // GDPR banner might not be present
    
    
      // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Now test privacy preferences
    await driver.get("http://localhost/multiflexi/main.php")
    {
      const element = await driver.findElement(By.css(".card:nth-child(14) .card-img-top"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("#iclassfasfa-user-shieldiPrivacy > .fas")).click()
    await driver.findElement(By.linkText("Privacy Preferences")).click()
    await driver.findElement(By.id("saveconsentpreferencesbutton")).click()
  })
})
