// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('runTemplates', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('runTemplates', async function() {
    // Login first
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);

    
    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.sleep(1000)
    
    // Now test run templates
    await driver.get("http://localhost/multiflexi/main.php")
    
    // Wait for page to load and click on Applications menu
    const appsMenu = await driver.wait(until.elementLocated(By.id("imgwidth30srcimagesappssvgApplications")), 5000)
    await appsMenu.click()
    await driver.findElement(By.linkText("⚗️RunTemplates")).click()
    
    // Wait for table to load and select last app in list using CSS selector
    await driver.sleep(1000)
    const lastAppRow = await driver.wait(until.elementLocated(By.css("tbody tr:last-child")), 5000)
    await lastAppRow.click()
    
    // Click on the action in the last row
    await driver.sleep(500)
    const lastActionLink = await driver.findElement(By.css("tbody tr:last-child a > span"))
    await lastActionLink.click()
  })
})
