// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search', async function() {
    // First, login
    await driver.get("http://localhost/multiflexi/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner using reusable function
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);
  
    
    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);
    
    // Wait for login to complete
    await driver.wait(until.urlContains("main.php"), 5000)
    
    // Open search menu
    await driver.findElement(By.id("mainmenusearchbutton")).click()
    
    // Wait for search results and select last position using CSS selector
    await driver.sleep(1000)
    const searchItems = await driver.findElements(By.css("#mainmenusearchbutton + ul li"))
    if (searchItems.length > 0) {
      await driver.findElement(By.css(`#mainmenusearchbutton + ul li:nth-child(${searchItems.length}) > a`)).click()
    }
  })
})
