// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('deleteApplication', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('deleteApplication', async function() {
    // Go to login page and maximize
    await driver.get("https://vyvojar.spoje.net/multiflexi/logout.php")
    await driver.manage().window().maximize()

    // Handle GDPR consent banner
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);

    // Login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);

    // Wait for login to complete
    await driver.sleep(1000);

    // Now perform delete application actions
    await driver.get("https://vyvojar.spoje.net/multiflexi/main.php")
    await driver.manage().window().setRect({ width: 1925, height: 1033 })
    await driver.findElement(By.id("imgwidth30srcimagesappssvgApplications")).click()
    await driver.findElement(By.linkText("🧩Application list")).click()
    // Click the last application in the list using a CSS selector
    const lastAppRow = await driver.findElement(By.css("table tbody tr:last-child a"));
    await lastAppRow.click();
    await driver.findElement(By.linkText("🪦 Remove")).click()
  })
})
