// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('deleteCompani', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('deleteCompani', async function() {
    // Go to login page and maximize
    await driver.get("https://vyvojar.spoje.net/multiflexi/logout.php")
    await driver.manage().window().maximize()

    // Handle GDPR consent banner
    const handleGdprConsent = require('./gdpr.js');
    await handleGdprConsent(driver);

    // Login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);

    // Wait for login to complete
    await driver.sleep(1000);

    // Now perform delete company actions
    await driver.get("https://vyvojar.spoje.net/multiflexi/main.php")
    await driver.manage().window().setRect(1925, 1033)
    await driver.findElement(By.id("imgwidth30srcimagescompanysvgCompanies")).click()
    await driver.findElement(By.linkText("Listing")).click()
    // Select and delete the last company in the list using CSS selector
    const lastDeleteButton = await driver.findElement(By.css("table tbody tr:last-child #deletecompanybutton"));
    await lastDeleteButton.click();
    await driver.findElement(By.css(".btn-danger")).click()
  })
})
