// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');

(async () => {
  let driver;
  try {
    driver = await new Builder().forBrowser('chrome').build();
    // First, login with credentials from createFirstAdminAcc
    await driver.get("http://localhost/multiflexi/logout.php");
    // Set window to maximum available screen resolution
    const {width, height} = await driver.executeScript(() => ({ width: window.screen.width, height: window.screen.height }));
    await driver.manage().window().setRect(0, 0, width, height);

    // Handle GDPR consent banner
    try {
      const gdprAcceptButton = await driver.wait(until.elementLocated(By.id("consent-accept-all")), 3000);
      await gdprAcceptButton.click();
      await driver.sleep(500);
    } catch (e) {
      // GDPR banner might not be present
    }

    // Perform login using reusable function
    const loginWithAdminCredentials = require('./login.js');
    await loginWithAdminCredentials(driver);

    // Wait for login to complete and navigate to main page
    await driver.wait(until.urlContains("main.php"), 5000);

    // Now sign off
    await driver.findElement(By.linkText("Sign Off")).click();

    if (driver) await driver.quit();
    process.exit(1); // Success: return 1
  } catch (error) {
    if (driver) await driver.quit();
    process.exit(0); // Error: return 0
  }
})();
